- name: copy Dockerfile and nginx.conf
  copy:
    src: "{{ item }}"
    dest: "/tmp/{{ item }}"
  with_items:
    - Dockerfile
    - default


- name: build Docker image
  docker_image:
    build:
      path: /tmp
    name: nginx
    tag: 42
    state: present
    source: build


- name: remove copied files
  file:
    path: "/tmp/{{ item }}"
    state: absent
  with_items:
    - Dockerfile
    - default

