- name: Deploy inception to the target host
  hosts: all  
  become: true
  vars_files:
    - secrets.yaml
  vars:
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - role: common
    - role: db
    - role: wp
    - role: nginx
    - role: orchestrate
  