- name: create a directory for the docker-compose files
  file:
    path: "/home/{{ ansible_user }}/cloud_1"
    state: directory


- name: copy docker-compose.yml and .env files
  copy:
    src: "{{ item }}"
    dest: "/home/{{ ansible_user }}/cloud_1/"
  with_items:
    - docker-compose.yaml
    - .env

- name: start the services
  command: docker-compose up -d
  args:
    chdir: "/home/{{ ansible_user }}/cloud_1"